name: Format, Build, Test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Cache .NET Packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore Dependencies
      run: dotnet restore

    - name: Verify Formatting
      run: dotnet format --verify-no-changes --verbosity detailed

  generate-tests:
    runs-on: ubuntu-latest
    needs: format

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai gitpython

    - name: Run unit test generation script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        REPO_PATH: ${{ github.workspace }}
        SRC_DIR: WSAPIR
        TEST_DIR: WSAPIR.Tests
      run: |
        python generate_tests.py

  run-tests:
    runs-on: ubuntu-latest
    needs: generate-tests

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Cache .NET Packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: '**/TestResults/*.trx'
