name: Nightly Release

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-and-merge:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    steps:
    - name: Generate Github Actions App token
      id: app-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ vars.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
        repositories: release

    - name: Merge development -> release
      uses: devmasx/merge-branch@master
      with:
        type: now
        from_branch: dev
        target_branch: release
        github_token: ${{ steps.app-token.outputs.token }}


