name: Nightly Release

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-and-merge:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    permissions:
      contents: write 

    steps:
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ vars.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
    - uses: actions/checkout@master

    - name: Install GitHub CLI
      run: sudo apt-get install gh

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Merge development -> release
      uses: devmasx/merge-branch@master
      with:
        type: now
        from_branch: dev
        target_branch: release
        github_token: ${{ steps.app-token.outputs.token }}


