name: Release

on:
  push:
    tags:
      - "v*"
    branches:
      - release

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          ref: release

      - name: Run Automatic release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false