name: Generate and Run Unit Tests

on:
  push:
    branches:
      - generatedTests
  pull_request:
    branches:
      - generatedTests

jobs:
  generate-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai gitpython

    - name: Run unit test generation script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        REPO_PATH: ${{ github.workspace }}
        SRC_DIR: src
        TEST_DIR: WSAPIR.Tests
      run: |
        python generate_tests.py

  run-tests:
    runs-on: ubuntu-latest
    needs: generate-tests
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --configuration Release